music_app/albums/urls.py
from django.urls import path, include
from music_app.albums.views import CreateAlbumView, DetailAlbumView, EditAlbumView, DeleteAlbumView

urlpatterns = (
    path("add/", CreateAlbumView.as_view(), name="create_album"),
    path("<int:pk>/",
         include([
             path("details/", DetailAlbumView.as_view(), name="details_album"),
             path("edit/", EditAlbumView.as_view(), name="edit_album"),
             path("delete/", DeleteAlbumView.as_view(), name="delete_album"),
         ])
         )
)

music_app/profiles/urls.py
from django.urls import path

from music_app.profiles.views import DeleteProfileView, DetailProfileView

urlpatterns = (
    path("delete/", DeleteProfileView.as_view(), name="delete_profile"),
    path("details/", DetailProfileView.as_view(), name="details_profile")
)

music_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("music_app.web.urls")),
    path("album/", include("music_app.albums.urls")),
    path("profiles/", include("music_app.profiles.urls")),
]

music_app/web/urls.py
from django.urls import path
from music_app.web.views import index, create_profile

urlpatterns = [
    path("", index, name="index"),
    path("create-profile/", create_profile, name="create_profile")
]

music_app/albums/models.py
from django.core.validators import MinValueValidator
from django.db import models
from music_app.profiles.models import Profile


class Album(models.Model):
    MAX_ALBUM_NAME_LENGTH = 30
    MAX_ARTIST_NAME_LENGTH = 30
    MIN_PRICE = 0.0
    MAX_GENRE_LENGTH = 30

    GENRE_POP_MUSIC = "Pop Music"
    GENRE_JAZZ_MUSIC = "Jazz Music"
    GENRE_ROCK_MUSIC = "Rock Music"
    GENRE_COUNTRY_MUSIC = "Country Music"
    GENRE_RNB_MUSIC = "R&B Music"
    GENRE_DANCE_MUSIC = "Dance Music"
    GENRE_HIP_HOP_MUSIC = "Hip Hop Music"
    GENRE_OTHER = "Other"

    GENRES = (
        (GENRE_POP_MUSIC, GENRE_POP_MUSIC),
        (GENRE_JAZZ_MUSIC, GENRE_JAZZ_MUSIC),
        (GENRE_ROCK_MUSIC, GENRE_ROCK_MUSIC),
        (GENRE_COUNTRY_MUSIC, GENRE_COUNTRY_MUSIC),
        (GENRE_RNB_MUSIC, GENRE_RNB_MUSIC),
        (GENRE_DANCE_MUSIC, GENRE_DANCE_MUSIC),
        (GENRE_HIP_HOP_MUSIC, GENRE_HIP_HOP_MUSIC),
        (GENRE_OTHER, GENRE_OTHER)
    )

    name = models.CharField(
        max_length=MAX_ALBUM_NAME_LENGTH,
        unique=True,
        null=True,
        blank=True,
        verbose_name="Album name"
    )

    artis_name = models.CharField(
        max_length=MAX_ARTIST_NAME_LENGTH,
        null=False,
        blank=False,
        verbose_name="Artist"
    )

    description = models.TextField(
        null=True,
        blank=True,
    )

    image_url = models.URLField(
        null=False,
        blank=False,
        verbose_name="Image URL"
    )

    price = models.FloatField(
        null=False,
        blank=False,
        validators=(
            MinValueValidator(MIN_PRICE),
            ),
    )

    owner = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
    )

    genre = models.CharField(
        max_length=MAX_GENRE_LENGTH,
        choices=GENRES,
        null=False,
        blank=False,
    )

music_app/profiles/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.db import models


def validate_username(username):
    is_valid = all(ch.isalnum() or ch == "_" for ch in username)
    if not is_valid:
        raise ValidationError("Username name must contains only letters, numbers and underscore")


class Profile(models.Model):
    MIN_USERNAME_LENGTH = 2
    MAX_USERNAME_LENGTH = 15

    username = models.CharField(
        max_length=MAX_USERNAME_LENGTH,
        validators=(
            MinLengthValidator(MIN_USERNAME_LENGTH),
        ),
        null=False,
        blank=False,
    )

    email = models.EmailField(
        null=False,
        blank=False,
    )

    age = models.PositiveIntegerField(
        null=True,
        blank=True,
    )

music_app/web/models.py
from django.db import models

# Create your models here.

music_app/web/forms.py
from django import forms

from music_app.profiles.models import Profile


class CreateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["username", "email", "age"]
        widgets = {
            "username": forms.TextInput(attrs={"placeholder": "Username"}),
            "email": forms.EmailInput(attrs={"placeholder": "Email"}),
            "age": forms.NumberInput(attrs={"placeholder": "Age"})
        }

music_app/albums/views.py
from django.forms import modelform_factory
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from music_app.albums.models import Album
from music_app.web.views import get_profile


class AlbumFormMixin:
    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["name"].widget.attrs["placeholder"] = "Album Name"
        form.fields["artis_name"].widget.attrs["placeholder"] = "Artist"
        form.fields["description"].widget.attrs["placeholder"] = "Description"
        form.fields["price"].widget.attrs["placeholder"] = "Price"
        form.fields["image_url"].widget.attrs["placeholder"] = "Image URL"
        return form


class ReadOnlyMixin:
    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)

        for field in form.fields.values():
            field.widget.attrs["readonly"] = "readonly"

        return form


class CreateAlbumView(AlbumFormMixin, CreateView):
    queryset = Album.objects.all()
    fields = ["name", "artis_name", "genre", "description", "image_url", "price"]
    template_name = "albums/album-add.html"
    success_url = reverse_lazy("index")

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner = get_profile()
        
        return super().form_valid(form)


class DetailAlbumView(DetailView):
    queryset = Album.objects.all()
    template_name = "albums/album-details.html"


class EditAlbumView(AlbumFormMixin, UpdateView):
    queryset = Album.objects.all()
    fields = ["name", "artis_name", "genre", "description", "image_url", "price"]
    template_name = "albums/album-edit.html"
    success_url = reverse_lazy("index")


class DeleteAlbumView(ReadOnlyMixin, DeleteView):
    queryset = Album.objects.all()
    template_name = "albums/album-delete.html"
    success_url = reverse_lazy("index")
    form_class = modelform_factory(Album, fields=["name", "artis_name", "genre", "description", "image_url", "price"])

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["instance"] = self.object

        return kwargs

music_app/profiles/views.py
from django.urls import reverse_lazy
from django.views.generic import DetailView, DeleteView
from music_app.profiles.models import Profile
from music_app.web.views import get_profile


class DetailProfileView(DetailView):
    queryset = Profile.objects.all()
    template_name = "profiles/profile-details.html"

    def get_object(self, queryset=None):
        return get_profile()


class DeleteProfileView(DeleteView):
    template_name = "profiles/profile-delete.html"
    success_url = reverse_lazy("index")

    def get_object(self, queryset=None):
        return get_profile()

music_app/web/views.py
from django.shortcuts import render, redirect

from music_app.albums.models import Album
from music_app.profiles.models import Profile
from music_app.web.forms import CreateProfileForm


def get_profile():
    return Profile.objects.first()


def create_profile(request):
    form = CreateProfileForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect("index")

    context = {
        "form": form,
        "no_nav": True
    }

    return render(request, "web/home-no-profile.html", context)


def index(request):
    profile = get_profile()

    if profile is None:
        return create_profile(request)

    context = {
        "albums": Album.objects.all()
    }

    return render(request, "web/home-with-profile.html", context)

templates/albums/album-add.html
{% extends "base.html" %}
{% block main_content %}
      <!-- Main Content -->
      <!--Create Page-->
      <section class="createPage">
        <form action="{% url "create_album" %}" method="post">
          <fieldset>
            <legend>Add Album</legend>
            <div class="container">
                {{ form }}
                <button class="add-album" type="submit">Add new album</button>
                {% csrf_token %}
            </div>
          </fieldset>
        </form>
      </section>
{% endblock %}

templates/albums/album-delete.html
{% extends "base.html" %}
{% block main_content %}
      <!-- Main Content -->

      <!--Delete Page-->
      <section class="editPage">
        <form action="{% url 'delete_album' pk=object.pk %}" method="post">
          <fieldset>
            <legend>Delete Album</legend>
            <div class="container">
             {{ form }}
              <!-- Button for Deleting an Album -->
              <button class="delete-album" type="submit">Delete Album</button>
                {% csrf_token %}
            </div>
          </fieldset>
        </form>
      </section>
{% endblock %}

templates/albums/album-details.html
{% extends "base.html" %}
{% block main_content %}
      <!-- Main Content -->
      <!--Details Page-->
      <section id="detailsPage">
        <div class="wrapper">
          <div class="albumCover">
            <!-- Album Image -->
            <img src="{{ object.image_url}}" alt="{{ object.description }}" />
          </div>

          <div class="albumInfo">
            <div class="albumText">
              <!-- Album Info -->
              <h1>Name: {{ object.name }}</h1>
              <h3>Artist: {{ object.artis_name }}</h3>
              <h4>Genre: {{ object.genre }}</h4>
              <h4>Price: ${{ object.price|floatformat:2}}</h4>
              <p>
                Description: {{ object.description}}
              </p>
            </div>

            <div class="actionBtn">
              <!-- Album Buttons -->
              <a href="{% url 'edit_album' pk=object.pk %}" class="edit">Edit</a>
              <a href="{% url 'delete_album' pk=object.pk %}" class="remove">Delete</a>
            </div>
          </div>
        </div>
      </section>
{% endblock %}

templates/albums/album-edit.html
{% extends "base.html" %}
{% block main_content %}
      <!-- Main Content -->
      <!--Edit Page-->
      <section class="editPage">
        <form action="{% url 'edit_album' pk=object.pk %}" method="post">
          <fieldset>
            <legend>Edit Album</legend>
            <div class="container">
              <!-- Form for Editing Album -->
              {{ form }}
              <button class="edit-album" type="submit">Edit Album</button>
              {% csrf_token %}  
            </div>
          </fieldset>
        </form>
      </section>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>My Music App</title>
    <!-- Static Load -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>

  <body>
    <div id="box">
      <!-- Navigation Bar -->
      <header>
        <nav>
          <img src="{% static 'images/headphones.png' %}" alt="headphones" />
          <a href="{% url 'index' %}">Home</a>
          {% if not no_nav %}
          <ul>
            <!--Only for user with created profile-->
            <li><a href="{% url 'create_album' %}">Create Album</a></li>
            <li><a href="{% url 'details_profile' %}">Profile</a></li>
          </ul>
          {% endif %}  
        </nav>
      </header>
      <!-- End Navigation Bar -->
    <!-- Footer -->
      <footer>
        <div>&copy;SoftUni Team 2024. All rights reserved.</div>
      </footer>
      <!-- End Footer -->
    </div>
  </body>
</html>
{%  block main_content %}
{% endblock %}

templates/profiles/profile-delete.html
{% extends "base.html" %}
{% block main_content %}
    }
      <!-- End Navigation Bar -->

      <!-- Main Content -->
      <!-- Delete Profile Page-->
      <section id="detailsPage">
        <div class="wrapper">
          <div class="profileText">
            <!-- Delete Profile Form -->
            <h1>Are you sure you want to delete your profile?</h1>
            <form action="{% url 'delete_profile' %}" method="post">
              <button class="delete-profile" type="submit">Delete</button>
                {% csrf_token %}
            </form>
            <!-- End Delete Profile Form -->
          </div>
        </div>
      </section>
{% endblock %}

templates/profiles/profile-details.html
{% extends "base.html" %}
{% block main_content %}
      <!-- Main Content -->
      <!--Details Page-->
      <section id="detailsPage">
        <div class="wrapper">
          <div class="profilePage">
            <img
              src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png"
              alt="Profile Image"
            />
          </div>

          <div class="profileText">
            <!-- Profile Info -->
            <h1>Username: {{ object.username }}</h1>
            <h1>Email: {{ object.email }}</h1>
            <h1>Age: {{ object.age }}</h1>
            <h1>Albums: {{ object.album_set.count }}</h1>
          </div>

          <div class="actionBtn">
            <!-- Button for Deleting the Profile -->
            <a href="{% url 'delete_profile' %}" class="remove">Delete</a>
          </div>
        </div>
      </section>
{% endblock %}

templates/web/home-no-profile.html
{%  extends "base.html" %}
{% load static %}
{% block main_content %}
<!-- Main Content -->
      <!--Home Page-->
      <div class="container-inline" xmlns="http://www.w3.org/1999/html">
        <section id="welcomePage">
          <div id="welcome-message">
            <h1>Welcome to</h1>
            <h1>My Music App!</h1>
          </div>
          <div class="music-img">
            <img src="{% static 'images/musicIcons.webp' %}" alt="music-icon" />
          </div>
        </section>

        <!-- Registration -->
        <section id="registerPage">
          <form action="{% url 'create_profile' %}" method="post">
            <fieldset>
              <legend>Profile</legend>
              {{ form }}
              <button type="submit" class="register">Enter</button>  
              {% csrf_token %}  
            </fieldset>
          </form>
        </section>
      </div>
{% endblock %}

templates/web/home-with-profile.html
{% extends "base.html" %}
{% load static %}
{% block main_content %}
  <!-- Main Content -->
  <!-- Catalog with Albums-->
  <section id="catalogPage">
    <!--  If No albums in catalog -->
        <!-- If albums in catalog -->
    <h1>All Albums</h1>
    <!-- First Card-Box in catalog -->
      {% for album in albums %}
    <div class="card-box">
      <img src="{{ album.image_url }}" alt="{{ album.description }}"/>
      <div>
        <div class="text-center">
          <p class="name">Name: {{ album.name}}</p>
          <p class="artist">Artist: {{ album.artis_name}}</p>
          <p class="genre">Genre: {{ album.genre }}</p>
          <p class="price">Price: ${{ album.price|floatformat:2}}</p>
        </div>
        <div class="btn-group">
          <a href="{% url 'details_album' pk=album.pk %}">Details</a>
        </div>
      </div>
    </div>
    <!-- End Second Card-Box in catalog -->

    <!-- Third Card-Box in catalog -->
        {% empty %}
    <p>No Albums in Catalog!</p>
    {% endfor %}
    <!-- End Third Card-Box in catalog -->
  </section>
{% endblock %}